pipelines:
  email-components:
    group: Dependencies
    label_template: "${COUNT}"
    materials:
      email-components-git:
        git: https://github.com/ukparliament/email-components.git
        branch: master
        auto_update: true
    stages:
      - build:
          approval: manual
          jobs:
            build:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - checkout_to_release
                - exec:
                    run_if: passed
                    command: npm
                    arguments:
                      - install
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - build_s3
      - deploy:
          jobs:
            build:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release
environments:
  Web.DEVCI:
    pipelines:
      - email-components
